# Generated by Django 3.0 on 2020-04-13 08:50
# Generated by Django 2.2.6 on 2020-04-13 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import videos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(max_length=300)),
                ('creation_time', models.DateTimeField(default='2020-04-13 14:20:13.320235')),
                ('creation_time', models.DateTimeField(default='2020-04-13 19:41:45.516705')),
                ('video_url', models.URLField()),
                ('catagory', models.CharField(choices=[('cse', 'Computer Science'), ('phs', 'Philosphy'), ('phy', 'Physics'), ('mda', 'Media'), ('mth', 'Methametics'), ('art', 'Arts'), ('chy', 'Chemistry'), ('bio', 'Biology')], max_length=3)),
                ('notes', models.FileField(blank=True, null=True, upload_to=videos.models.file_upload_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ManyToManyField(to='videos.Video')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ManyToManyField(null=True, to='videos.Video')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=300)),
                ('creation_time', models.DateTimeField(default='2020-04-13 14:20:13.322232')),
                ('creation_time', models.DateTimeField(default='2020-04-13 19:41:45.518705')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='videos.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Video')),
            ],
        ),
    ]
