# Generated by Django 2.2.6 on 2020-04-11 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 11, 19, 7, 30, 375677)),
        ),
        migrations.AlterField(
            model_name='video',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 11, 19, 7, 30, 375677)),
        ),
    ]
