<<<<<<< HEAD:videos/migrations/0002_auto_20200413_1416.py
# Generated by Django 2.2.6 on 2020-04-13 08:46
=======
# Generated by Django 2.1 on 2020-04-13 12:20
>>>>>>> b7609a39eb42d238b094c98c65b27d5c3f89d402:videos/migrations/0002_auto_20200413_1750.py

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creation_time',
<<<<<<< HEAD:videos/migrations/0002_auto_20200413_1416.py
            field=models.DateTimeField(default='2020-04-13 14:16:06.424301'),
=======
            field=models.DateTimeField(default='2020-04-13 17:50:08.784768'),
>>>>>>> b7609a39eb42d238b094c98c65b27d5c3f89d402:videos/migrations/0002_auto_20200413_1750.py
        ),
        migrations.AlterField(
            model_name='video',
            name='creation_time',
<<<<<<< HEAD:videos/migrations/0002_auto_20200413_1416.py
            field=models.DateTimeField(default='2020-04-13 14:16:06.424301'),
=======
            field=models.DateTimeField(default='2020-04-13 17:50:08.784768'),
>>>>>>> b7609a39eb42d238b094c98c65b27d5c3f89d402:videos/migrations/0002_auto_20200413_1750.py
        ),
    ]
