# Generated by Django 3.0.4 on 2020-04-11 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='catagory',
            field=models.CharField(choices=[('cse', 'Computer Science'), ('phs', 'Philosphy'), ('phy', 'Physics'), ('mda', 'Media'), ('che', 'Chemistry'), ('bio', 'Biology')], default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 11, 20, 32, 26, 930275)),
        ),
        migrations.AlterField(
            model_name='video',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 11, 20, 32, 26, 929277)),
        ),
    ]
