# Generated by Django 3.0.4 on 2020-04-09 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 18, 25, 19, 745185)),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
