# Generated by Django 2.2.6 on 2020-04-11 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20200411_2032'),
        ('videos', '0002_auto_20200411_1907'),
    ]

    operations = [
    ]
