# Generated by Django 2.2.6 on 2020-04-12 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_merge_20200411_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 12, 11, 5, 25, 200099)),
        ),
        migrations.AlterField(
            model_name='video',
            name='catagory',
            field=models.CharField(choices=[('cse', 'Computer Science'), ('phs', 'Philosphy'), ('phy', 'Physics'), ('mda', 'Media'), ('mth', 'Methametics'), ('art', 'Arts'), ('chy', 'Chemistry'), ('bio', 'Biology')], max_length=3),
        ),
        migrations.AlterField(
            model_name='video',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 12, 11, 5, 25, 198097)),
        ),
    ]
