# Generated by Django 2.2.6 on 2020-04-12 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20200412_1105'),
        ('videos', '0003_auto_20200412_0135'),
    ]

    operations = [
    ]
