# Generated by Django 3.0.4 on 2020-04-09 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20200409_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='replay',
            new_name='reply',
        ),
        migrations.AlterField(
            model_name='comment',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 0, 59, 49, 949884)),
        ),
        migrations.AlterField(
            model_name='video',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 0, 59, 49, 949884)),
        ),
    ]
