# Generated by Django 3.0.4 on 2020-04-09 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20200410_0059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reply',
            new_name='parent',
        ),
        migrations.AlterField(
            model_name='comment',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 1, 18, 5, 994791)),
        ),
        migrations.AlterField(
            model_name='video',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 1, 18, 5, 993793)),
        ),
    ]
