# Generated by Django 2.2.6 on 2020-04-13 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_auto_20200413_0654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='myvideos',
            new_name='video',
        ),
        migrations.AlterField(
            model_name='comment',
            name='creation_time',
            field=models.DateTimeField(default='2020-04-13 07:03:55.510058'),
        ),
        migrations.AlterField(
            model_name='video',
            name='creation_time',
            field=models.DateTimeField(default='2020-04-13 07:03:55.507056'),
        ),
    ]
