# Generated by Django 2.1 on 2020-04-10 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_auto_20200410_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 9, 56, 53, 689464)),
        ),
        migrations.AlterField(
            model_name='video',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 9, 56, 53, 688465)),
        ),
    ]
