# Generated by Django 2.2.6 on 2020-04-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_auto_20200413_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creation_time',
            field=models.DateTimeField(default='2020-04-13 08:12:27.381856'),
        ),
        migrations.AlterField(
            model_name='video',
            name='creation_time',
            field=models.DateTimeField(default='2020-04-13 08:12:27.380354'),
        ),
    ]
