# Generated by Django 2.2.6 on 2020-04-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0012_auto_20200413_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creation_time',
            field=models.DateTimeField(default='2020-04-13 12:37:01.908308'),
        ),
        migrations.AlterField(
            model_name='video',
            name='creation_time',
            field=models.DateTimeField(default='2020-04-13 12:37:01.908308'),
        ),
    ]
