# Generated by Django 3.0.4 on 2020-04-10 13:38

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.FileField(default='profile_img/user.png', upload_to=account.models.get_image_name),
        ),
    ]
