# Generated by Django 2.1 on 2020-04-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='work_experience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
