# Generated by Django 3.0.3 on 2020-04-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200409_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='interests',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
