# Generated by Django 2.1 on 2020-04-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200411_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='institute',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='interests',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='institute',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='qualifications',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
