# Generated by Django 2.2.6 on 2020-04-12 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_survey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Survey',
        ),
    ]
